# Playbook create and written by: Travis Michette
# Contact information: tmichett@redhat.com
# Designed and Written for Fedora
---
- name: Installation of Gnome Extensions
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Enable Gnome Extension Desktop Icons
      ansible.builtin.command: gnome-extensions enable ding@rastersoft.com

    - name: Enable Gnome Extension Create Desktop Shortcut
      ansible.builtin.command: gnome-extensions enable add-to-desktop@tommimon.github.com